all:
  children:
    sidekick:
      hosts:
        sidekick-1.homelab.uknth.me:
          ansible_host: 192.168.1.2
          ansible_user: ansible
          ansible_ssh_private_key_file: keys/ansible_rsa.private
          ansible_become_password: "{{ sudo_password }}"
    # hero:
    #   hosts:
    #     hero-1.homelab.uknth.me:
    #       ansible_host: 192.168.1.3