- name: Set up 'Persistence' for Config
  kubernetes.core.k8s:
    state: present
    template: "fast-storage.yaml.j2"

- name: Set up 'Persistence' for Media
  kubernetes.core.k8s:
    state: present
    template: "nas-storage.yaml.j2"

- name: Install 'jellyfin' from Docker Image
  kubernetes.core.k8s:
    state: present
    template: "jellyfin.yaml.j2"
