- name: create resolv-file for dnsmasq
  become: true
  ansible.builtin.copy:
    content: |
      nameserver 1.1.1.1
      nameserver 8.8.8.8
    dest: /etc/resolv.dnsmasq

- name: create hosts file
  become: true
  notify: Restart dnsmasq
  ansible.builtin.copy:
    force: true
    content: |
      127.0.0.1 localhost
      127.0.0.1 {{ inventory_hostname }}
      127.0.0.1 {{ ansible_hostname }}

      ::1     ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters


      192.168.1.2 dns.uknth.me
      192.168.1.2 homelab.uknth.me sidekick-1.homelab.uknth.me
      100.89.95.80 homelab.uknth.me sidekick-1.homelab.uknth.me

      192.168.1.3 hero-1.homelab.uknth.me

      100.89.95.80 grafana.homelab.uknth.me prometheus.homelab.uknth.me 
      100.89.95.80 proxmox.homelab.uknth.me portainer.homelab.uknth.me
      192.168.1.2 grafana.homelab.uknth.me prometheus.homelab.uknth.me 
      192.168.1.2 proxmox.homelab.uknth.me portainer.homelab.uknth.me

      192.168.1.3 k8s-hero-1.homelab.uknth.me

      # Kubernetes
      100.89.95.80 skooner.homelab.uknth.me {{ homelab_shiori_domain_name }}
      192.168.1.2 skooner.homelab.uknth.me {{ homelab_shiori_domain_name }}

    dest: /etc/hosts

- name: Check if dnsmasq is already present.
  ansible.builtin.command: which dnsmasq
  failed_when: false
  changed_when: false
  check_mode: false
  register: dnsmasq_command_result

- name: execute dnsmasq role
  become: true
  when: dnsmasq_command_result.rc == 1
  ansible.builtin.import_role:
    name: dnsmasq
  vars:
    dnsmasq_service_enabled: true
    # TODO: take the config for `listen-address` from config & tailscale command
    dnsmasq_dnsmasq_conf:
      - |
        port=53
        domain-needed
        bogus-priv
        strict-order
        bind-dynamic
        localise-queries
        listen-address=0.0.0.0
        listen-address=127.0.0.1
        listen-address=192.168.1.2
        listen-address=100.89.95.80
        resolv-file=/etc/resolv.dnsmasq
    dnsmasq_dnsmasq_d_files_present:
      cache:
        - |
          cache-size=100000
          min-cache-ttl=600
          no-poll
