- name: Display all hosts and their IP
  ansible.builtin.debug:
    msg: |
      {% for name, var in hostvars.items() %}
      {% if name != 'localhost' -%}
      - {{ name }}.puhome.net: {{ var.ansible_host | default(name) }}
      {% endif -%}
      {% endfor %}

- name: Create blocky directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ config_dir }}/blocky/compose"
    - "{{ config_dir }}/blocky/config"

- name: Copy templated blocky files into place.
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ config_dir }}/blocky/{{ item.dest }}"
    mode: 0644
  loop:
    - src: docker-compose.yml.j2
      dest: compose/docker-compose.yml
    - src: config.yml.j2
      dest: config/config.yml
  notify: Restart blocky

- name: Replace string in resolve file
  become: true
  replace:
    path: "/etc/resolv.conf"
    regexp: "127.0.0.53"
    replace: "127.0.0.1"

- name: Ensure 'systemd-resolved' is not runnning
  become: true
  ansible.builtin.systemd:
    state: stopped
    enabled: false
    name: systemd-resolved
  when: 
    - ansible_facts['os_family'] == 'Ubuntu'

- name: Ensure blocky-compose is running
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/blocky/compose"
    build: never
  become: false
