- name: Playbook for Gateway Nodes
  hosts: gateway
  roles:
    - name: system/package
      tags: ["packages", "apt"]

    - name: system/ntp
      tags: ["ntp"]
    
    - role: network/tailscale
      tags: ["network", "tailscale"]

    - role: system/docker
      tags: ["docker"]

    - role: network/blocky
      tags: ["network", "dns", "blocky"]

    - role: monitor/node_exporter
      tags: ["monitor", "prometheus", "node_exporter"]

    - role: ui/homer
      tags: ["docker", "container", "homer"]

    - role: network/nginx
      tags: ["network", "nginx"]