- name: Hero Playbook for 'hero' Hosts
  hosts: hero
  roles:
    - role: monitor/node_exporter
      tags: ["monitor", "prometheus", "node_exporter"]
      
    - role: k8s/tools/dashboard
      tags: ["k8s", "k8s-dashboard", "skooner"]

    # K8s Roles
    - role: k8s/tools/samba
      tags: ["k8s", "samba","k8s-samba" ,"k8s-config", "k8s-samba-csi"]
    
    - role: k8s/utils/shiori
      tags: ["k8s", "shiori", "k8s-app"]
    
    - role: k8s/media/jellyfin
      tags: ["k8s", "jellyfin", "k8s-app"]

    - role: k8s/media/navidrome
      tags: ["k8s", "navidrome", "k8s-app"]