- name: Hero Playbook for 'hero' Hosts
  hosts: hero
  roles:
    - role: network/tailscale
      tags: ["network", "tailscale"]

    - role: monitor/node_exporter
      tags: ["monitor", "prometheus", "node_exporter"]
    
    - role: network/samba
      tags: ["network", "samba"]

    - role: system/proxmox
      tags: ["system", "proxmox", "proxmox-install"]