- name: Hero Playbook for 'hero' Hosts
  hosts: hero
  roles:
    - role: network/tailscale
      tags: ["network", "tailscale"]

    - role: monitor/node_exporter
      tags: ["monitor", "prometheus", "node_exporter"]
    
    - role: network/samba
      tags: ["network", "samba"]

    - role: system/microk8s 
      tags: ["system", "microk8s", "kubernetes"] 

    - role: ui/k8s/dashboard
      tags: ["k8s", "k8s-dashboard"]