# pie-1
- name: minis/pie-1 roles
  hosts: pie-1
  roles:
    - name: system/packages/apt
      tags: ["system", "packages", "apt"]

    - name: system/packages/ntp
      tags: ["system", "ntp"]

    - role: docker/network/pi-hole
      tags: ["docker", "network", "dns", "pi-hole", "pihole"]

# pie-2
- name: minis/pie-2 roles
  hosts: pie-2
  roles:
    - name: system/packages/apt
      tags: ["system", "packages", "apt"]

    - name: system/packages/ntp
      tags: ["system", "ntp"]

    - role: system/packages/docker
      tags: ["system", "docker"]

    - role: system/network/tailscale
      tags: ["system", "network", "tailscale"]

    - role: docker/network/blocky
      tags: ["docker", "network", "dns", "blocky"]

    - role: docker/services/vaultwarden
      tags: ["docker", "service", "vaultwarden"]

    - role: docker/ui/homer
      tags: ["ui", "homer"]

    - role: system/network/nginx
      tags: ["system" , "network", "nginx"]

# sidekick-1
- name: minis/sidekick-1 roles
  hosts: sidekick-1
  roles:
    - name: system/packages/apt
      tags: ["system", "packages", "apt"]

    - name: system/packages/ntp
      tags: ["system", "ntp"]

    - role: system/packages/docker
      tags: ["system", "docker"]

    - role: system/network/samba
      tags: ["sidekick-1" ,"system", "network", "samba", "file-sharing"]
      vars:
        samba_share_root: "/mnt/fast2"
        samba_share_name: "fast-storage2"

    - role: system/network/syncthing
      tags: ["sidekick-1", "system", "network", "syncthing", "file-sync"]

    - role: docker/services/immich
      tags: ["sidekick-1", "docker", "immich"]

    - role: docker/services/whoogle
      tags: ["sidekick-1", "docker", "whoogle"]

    - role: docker/services/sourcebot
      tags: ["sidekick-1", "docker", "sourcebot"]

# hero-1
- name: megas/hero-1 roles
  hosts: hero-1
  roles:
    - name: system/packages/apt
      tags: ["system", "packages", "apt"]

    - name: system/packages/ntp
      tags: ["system", "ntp"]

    - role: system/packages/k3s
      tags: ["system", "k3s", "kubernetes"] 

    - role: system/network/samba
      tags: ["hero-1", "system", "network", "samba", "file-sharing"]
      vars:
          samba_share_root: "/mnt/databank"
          samba_share_name: "fast-storage"

    - role: k8s/tools/samba
      tags: ["k8s", "samba","secret" ,"samba-config", "csi"]

    - role: k8s/media/jellyfin
      tags: ["k8s", "jellyfin", "k8s-app"]

    - role: k8s/media/navidrome
      tags: ["k8s", "navidrome", "k8s-app"]
 
- name: workstation/workstation-1 roles
  hosts: workstation-1
  gather_facts: true
  roles:
    - name: system/packages/apt
      tags: ["system", "packages", "apt"]

    - name: system/packages/ntp
      tags: ["system", "ntp"]

    - role: system/packages/docker
      tags: ["system", "docker"]

    - role: system/packages/helm
      tags: ["system", "helm", "installer"]

    - role: system/packages/kind
      tags: ["system", "kind", "installer"]

    - role: system/packages/kubectl
      tags: ["system", "kubectl", "installer"]

    - role: dev/packages/go
      tags: ["dev", "go", "golang", "installer" ]

    - role: dev/packages/taskfile
      tags: ["dev", "taskfile", "task", "installer" ]

    - role: dev/packages/skaffold
      tags: ["dev", "skaffold", "installer"]

    - role: dev/packages/awscli
      tags: ["dev", "awscli", "installer"]

    - role: dev/packages/lazygit
      tags: ["dev", "lazygit", "installer"]

    - role: dev/packages/node
      tags: ["dev", "node", "installer"]
