- name: nases/nas-2 roles
  hosts: nas-2.host
  tasks:
    - name: Change owner of media base dir
      ansible.builtin.command: |
        chown -R {{ ansible_user }}:{{ ansible_user }} {{ media_base_dir }}
      become: true

    - name: Change owner of media storage dir
      ansible.builtin.command: |
        chown -R {{ ansible_user }}:{{ ansible_user }} {{ media_out_dir }}
      become: true

  roles:
    - role: packages/ops/mount-nas1
      tags: ["ops", "mount", "nas1"]

    - role: docker/services/vaultwarden
      tags: ["docker", "service", "vaultwarden"]

    - role: docker/services/fusion
      tags: ["docker", "service", "fusion"]
    
    - role: docker/media/arr
      tags: ["docker", "media", "arr"]

    - role: docker/media/jellyfin
      tags: ["docker", "media", "jellyfin"]

    - role: docker/services/immich
      tags: ["docker", "service", "immich"]

    - role: docker/media/music
      tags: ["docker", "media", "music"]
