roles:
  - src: https://github.com/artis3n/ansible-role-tailscale
    name: artis3n.tailscale
  - src: https://github.com/Oefenweb/ansible-dnsmasq
    name: dnsmasq
  - name: ansible-netdata
    src: https://github.com/mrlesmithjr/ansible-netdata
  - name: ansible-role-nodejs
    src: https://github.com/geerlingguy/ansible-role-nodejs
collections:
  - community.docker
