roles:
  - src: https://github.com/artis3n/ansible-role-tailscale
    name: artis3n.tailscale
  - src: https://github.com/Oefenweb/ansible-dnsmasq
    name: dnsmasq
  - name: geerlingguy.node_exporter
  - name: geerlingguy.ntp
  - name: geerlingguy.nginx
  - name: geerlingguy.certbot
  - name: geerlingguy.pip
  - name: ansible-portainer
    src: https://github.com/uknth/ansible-role-portainer
  - name: ansible_role_microk8s
    src: https://github.com/istvano/ansible_role_microk8s
collections:
  - community.docker
  - vladgh.samba
  - kubernetes.core
