roles:
  - src: https://github.com/artis3n/ansible-role-tailscale
    name: artis3n.tailscale
  - src: https://github.com/Oefenweb/ansible-dnsmasq
    name: dnsmasq
  - name: geerlingguy.node_exporter
  - name: geerlingguy.ntp
  - name: geerlingguy.nginx
  - name: geerlingguy.certbot
  - name: geerlingguy.pip
  - name: ansible-portainer
    src: https://github.com/uknth/ansible-role-portainer
  - name: ansible_role_microk8s
    src: https://github.com/istvano/ansible_role_microk8s
  - name: gantsign.golang
  - name: comcast.sdkman
  - name: gikeymarcia.neovim
  - name: geerlingguy.nodejs
  - src: https://gitlab.com/cbz-d-velop/public-ansible/ansible-role-labocbz-install-pihole/-/archive/develop/ansible-role-labocbz-install-pihole-develop.tar.gz
    name: role.pihole
  - src: https://github.com/gikeymarcia/ansible-role-neovim
    name: role.neovim
collections:
  - community.docker
  - community.general
  - vladgh.samba
  - kubernetes.core
