roles:
  - src: https://github.com/artis3n/ansible-role-tailscale
    name: artis3n.tailscale
  - src: https://github.com/Oefenweb/ansible-dnsmasq
    name: dnsmasq
  - name: geerlingguy.node_exporter
  - name: geerlingguy.ntp
  - name: geerlingguy.nginx
  - name: geerlingguy.certbot
  - name: ansible-portainer
    src: https://github.com/uknth/ansible-role-portainer
collections:
  - community.docker
