roles:
  - src: https://github.com/artis3n/ansible-role-tailscale
    name: artis3n.tailscale
  - src: https://github.com/Oefenweb/ansible-dnsmasq
    name: dnsmasq
  - name: geerlingguy.node_exporter
  - name: geerlingguy.ntp
  - name: geerlingguy.nginx
collections:
  - community.docker
