- name: Sidekick Playbook for 'sidekick' hosts
  hosts: sidekick
  roles:
    - name: system/package
      tags: ["packages", "apt"]

    - name: system/ntp
      tags: ["ntp"]

    - role: system/docker
      tags: ["docker"]

    - role: monitor/prometheus-grafana-docker
      tags: ["docker", "container", "monitoring", "prometheus", "grafana"]

    - role: monitor/statping
      tags: ["docker", "container", "monitoring", "statping"]

    - role: network/syncthing
      tags: ["network", "storage", "syncthing"]
