- name: Sidekick Playbook for 'sidekick' hosts
  hosts: sidekick
  roles:
    - role: system/docker
      tags: ["docker"]

    - role: system/portainer
      tags: ["docker","container", "portainer"]

    - role: network/tailscale
      tags: ["network", "tailscale"]

    # - role: network/dnsmasq
    #   tags: ["network", "dns", "dnsmasq"]

    - role: network/blocky
      tags: ["network", "dns", "blocky"]

    - role: monitor/prometheus-grafana-docker
      tags: ["docker", "container", "monitoring", "prometheus", "grafana"]

    - role: ui/homer
      tags: ["docker", "container", "homer"]
    
    - role: network/nginx
      tags: ["network", "nginx"]