- name: Workstation Playbook for 'workstation' hosts
  hosts: workstation
  roles:
    - role: system/docker
      tags: ["docker"]

    - role: network/tailscale
      tags: ["network", "tailscale"]

    - role: system/portainer
      tags: ["docker", "container", "portainer"]

    - role: monitor/node_exporter
      tags: ["monitor", "prometheus", "node_exporter"]

    - role: dev/go
      tags: ["dev", "golang", "go"]

    - role: dev/sdkman
      tags: ["dev", "sdkman", "java"]

    - role: dev/neovim
      tags: ["dev", "neovim"]
