- name: Make directory for copying files
  ansible.builtin.command: |
    mkdir -p {{ config_dir }}/vaultwarden/data


- name: Copy docker compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ config_dir }}/vaultwarden/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Deploy vaultwarden using docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/vaultwarden"
    

