- name: Ensure fusion data and compose directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ fusion_root_dir }}/data"
    - "{{ fusion_root_dir }}/compose"

- name: Copy docker compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ fusion_root_dir }}/compose/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: Restart fusion

- name: Deploy fusion using docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ fusion_root_dir }}/compose"
    

