- name: Make directory for copying files
  ansible.builtin.command: |
    mkdir -p {{ vw_root_dir }}/compose

- name: Make directory for copying files
  ansible.builtin.command: |
    mkdir -p {{ vw_data_dir }}

- name: Copy docker compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ vw_root_dir }}/compose/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Deploy vaultwarden using docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ vw_root_dir }}/compose"
    

