- name: "Install 'proxmox' using proxmox role"
  become: true
  ansible.builtin.import_role:
    name: lae.proxmox

- name: Setup certificate using 'certbot'
  become: true
  ansible.builtin.import_role:
    name: "network/certbot"
  vars:
    certbot_install_method: package
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services: []
    certbot_auto_renew: true
    certbot_auto_renew_hour: "3"
    certbot_auto_renew_minute: "30"
    certbot_admin_email: uknth@outlook.com
    certbot_cloudflare_email: uknth@outlook.com
    certbot_cloudflare_api_key: "{{ cloudflare_api_key }}"
    certbot_certs:
      - domains:
          - "*.homelab.uknth.me"

- name: Create directory
  become: true
  ansible.builtin.command: |
    mkdir -p /etc/pve/local

- name: Copy 'private key' file to the destination
  become: true
  ansible.builtin.command: |
    cp -RH /etc/letsencrypt/live/homelab.uknth.me/privkey.pem /etc/pve/local/pveproxy-ssl.key

- name: Copy 'public key' file to the destination
  become: true
  ansible.builtin.command: |
    cp -RH /etc/letsencrypt/live/homelab.uknth.me/fullchain.pem /etc/pve/local/pveproxy-ssl.pem
  notify:
    - restart pveproxy
