- name: Set up 'Persistence' for config
  kubernetes.core.k8s:
    state: present
    template: "fast-storage.yaml.j2"

- name: Set up 'Persistence' for config
  kubernetes.core.k8s:
    state: present
    template: "fast-storage-config.yaml.j2"

- name: Set up 'Persistence' for downloads
  kubernetes.core.k8s:
    state: present
    template: "nas-storage.yaml.j2"

- name: Create 'Configmap' with transmission Config
  k8s:
    state: present
    definition: "{{ lookup('template', './configmap.yaml.j2') | from_yaml }}"

- name: Install 'transmission' from Docker Image
  kubernetes.core.k8s:
    state: present
    template: "transmission.yaml.j2"
