---
- name: Assert media mount is present
  ansible.builtin.command: "findmnt --target {{ jellyfin_data_dir }}"
  changed_when: false

- name: Create jellyfin directories
  become: true
  ansible.builtin.file:
    path: "{{ jellyfin_root_dir }}/{{ item }}"
    state: directory
    owner: "{{ jellyfin_puid }}"
    group: "{{ jellyfin_pgid }}"
    mode: "0755"
  loop: ["", compose, config, jellyseerr]

- name: Template jellyfin compose
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ jellyfin_root_dir }}/compose/docker-compose.yml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  notify: Restart jellyfin

- name: Deploy jellyfin + jellyseerr
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ jellyfin_root_dir }}/compose"
    project_name: jellyfin
    state: present
    pull: missing
