---
- name: Create mixarr dirs
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
  loop:
    - "{{ mixarr_root_dir }}"
    - "{{ mixarr_root_dir }}/compose"
    - "{{ mixarr_root_dir }}/data"
- name: Template mixarr compose
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ mixarr_root_dir }}/compose/docker-compose.yml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  no_log: true
  notify: Restart mixarr
- name: Deploy mixarr
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ mixarr_root_dir }}/compose"
    project_name: "mixarr"
    state: present
    pull: missing
