---
- name: Restart openwebui
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ openwebui_compose_dir }}"
    project_name: "{{ openwebui_compose_project }}"
    state: restarted
