# Supported Flags
# no_docker: true -> Do not install docker
# no_dns: true -> Do not install dns

# Hosts in `unamanaged_hosts` group will not be managed by the playbooks, it is
# there for reference in the inventory list only.
# IOT server is `iot-1.host` and has Home-Assistant OS installed and managed from UI
# DNS server is `dns-1.host` and has Pi-Hole installed and managed from UI
# NAS server is `nas-1.host` and has Synology DSM installed and managed from UI
---
all:
  children:
    # Hosts for which we don't manage the packages & services, basically 
    # the ones where we aren't running Debian
    # These we will have to write custom logic for in playbook
    unmanaged_hosts:
      children:
        unmanged_controls:
          hosts:
            dns-1.host:
              ansible_host: 10.0.2.7
              ansible_user: "{{ user }}"
              ansible_become_password: "{{ sudo_password }}"
              ansible_ssh_private_key_file: keys/ansible_rsa.private

        unmanged_iots:
          hosts:
            iot-1.host:
              ansible_host: 10.0.2.124
              ansible_user: root
              ansible_ssh_private_key_file: keys/ansible_rsa.private
              ansible_become_password: "{{ sudo_password }}"

        unmanged_nases:
          hosts:
            nas-1.host:
              ansible_host: 10.0.2.3
              ansible_user: "{{ user }}"
              ansible_become_password: "{{ sudo_password }}"
              ansible_ssh_private_key_file: keys/ansible_rsa.private

    # Hosts for which we manage the packages & services
    managed_hosts:
      children:
        controls:
          hosts:
            gateway-1.host:
              # Distribution: Debian
              ansible_host: 10.0.2.2
              ansible_user: "{{ user }}"
              ansible_ssh_private_key_file: keys/ansible_rsa.private
              ansible_become_password: "{{ sudo_password }}"
              dns_host: true

            control-1.host:
              # Distribution: Ubuntu
              ansible_host: 10.0.2.4
              ansible_user: "{{ user }}"
              ansible_ssh_private_key_file: keys/ansible_rsa.private
              ansible_become_password: "{{ sudo_password }}"

        nases:
          hosts:
            nas-2.host:
              # Distribution: Debian
              ansible_host: 10.0.2.6
              ansible_user: "{{ user }}"
              ansible_become_password: "{{ sudo_password }}"
              ansible_ssh_private_key_file: keys/ansible_rsa.private
              
        workstations:
          hosts:
            workstation-1.host:
              # Distribution: Debian
              ansible_host: 10.0.2.5
              ansible_user: "{{ user }}"
              ansible_become_password: "{{ sudo_password }}"
              ansible_ssh_private_key_file: keys/ansible_rsa.private
