all:
  children:
    gateway:
      hosts:
        pie-2.homelab.uknth.me:
          ansible_host: 10.0.2.2
          ansible_user: ansible
          ansible_ssh_private_key_file: keys/ansible_rsa.private
          ansible_become_password: "{{ sudo_password }}"
  # todo: configure pie-hole from ansible
    sidekick:
      hosts:
        sidekick-1.homelab.uknth.me:
          ansible_host: 10.0.2.4
          ansible_user: ansible
          ansible_ssh_private_key_file: keys/ansible_rsa.private
          ansible_become_password: "{{ sudo_password }}"
    hero:
      hosts:
        hero-1.homelab.uknth.me:
          ansible_host: 10.0.2.6
          ansible_user: ansible
          ansible_ssh_private_key_file: keys/ansible_rsa.private
          ansible_become_password: "{{ sudo_password }}"
          
    workstation:
      hosts:
        workstation-1.homelab.uknth.me:
          ansible_host: 10.0.2.5
          ansible_user: ansible
          ansible_ssh_private_key_file: keys/ansible_rsa.private
          ansible_become_password: "{{ sudo_password }}"
