all:
  children:
    minis:
      hosts:
        pie-1:
          ansible_host: 10.0.2.7
          ansible_user: ansible
          ansible_ssh_private_key_file: keys/ansible_rsa.private
          ansible_become_password: "{{ sudo_password }}"

        pie-2:
          ansible_host: 10.0.2.2
          ansible_user: ansible
          ansible_ssh_private_key_file: keys/ansible_rsa.private
          ansible_become_password: "{{ sudo_password }}"

        sidekick-1:
          ansible_host: 10.0.2.4
          ansible_user: ansible
          ansible_ssh_private_key_file: keys/ansible_rsa.private
          ansible_become_password: "{{ sudo_password }}"
        
        pie-3:
          ansible_host: 10.0.2.124
          ansible_user: root
          ansible_ssh_private_key_file: keys/ansible_rsa.private
          ansible_become_password: "{{ sudo_password }}"

    heros:
      hosts:
        hero-1:
          ansible_host: 10.0.2.6
          ansible_user: ansible
          ansible_ssh_private_key_file: keys/ansible_rsa.private
          ansible_become_password: "{{ sudo_password }}"
          
    workstation:
      hosts:
        workstation-1:
          ansible_host: 10.0.2.5
          ansible_user: ansible
          ansible_ssh_private_key_file: keys/ansible_rsa.private
          ansible_become_password: "{{ sudo_password }}"
