- name: "Create statping home directory, if it doesn't exist"
  ansible.builtin.command: |
    mkdir -p {{ config_dir }}/statping

- name: Synchronize blocky directory.
  ansible.posix.synchronize:
    src: files/statping
    dest: "{{ config_dir }}"
    delete: false
    recursive: true
    perms: false
  become: false

- name: "Start Statping Docker Image"
  community.docker.docker_container:
    name: statping-homelab
    image: adamboutcher/statping-ng
    volumes:
      - "{{ config_dir }}/statping:/app"
    published_ports:
      - 0.0.0.0:9001:8080
    env:
      DB_CONN: sqlite
      REMOVE_AFTER: "360h"
      CLEANUP_INTERVAL: "24h"
      DISABLE_LOGS: "true"
      DOMAIN: "statping.{{ domain }}"
