- name: Setup Taskfile.dev on Server
  get_url:
    url: "https://taskfile.dev/install.sh"
    dest: "{{ data_dir }}/downloads/taskfile.sh"
    creates: "{{ data_dir }}/downloads/taskfile.sh"
    mode: 0755

- name: Change permission for script
  command:
    chmod 700 {{ data_dir }}/downloads/taskfile.sh

- name: Execute installer script
  become: true
  command: |
    sh {{ data_dir }}/downloads/taskfile.sh -d -b /usr/local/bin
