---
- name: install beszel-agent
  become: true
  ansible.builtin.import_role:
    name: dbrennand.beszel
  vars:
    # State of the Beszel binary agent installation
    beszel_state: present
    # Version of the Beszel binary agent to install
    # Can be a specific version from GitHub (e.g., v0.9.1)
    beszel_version: "{{ ba_version }}"
    # Port for the Beszel binary agent to listen on
    beszel_port: "{{ ba_port }}"
    # Public key used to authenticate the Beszel binary agent to the Hub
    beszel_public_key: "{{ ba_public_key }}"
    # Directory to install the Beszel binary agent into
    beszel_install_dir: "{{ ba_install_dir }}"