---
- name: Create ntfy dirs
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
  loop:
    - "{{ ntfy_root_dir }}"
    - "{{ ntfy_root_dir }}/compose"
    - "{{ ntfy_root_dir }}/config"
    - "{{ ntfy_root_dir }}/cache"
    - "{{ ntfy_root_dir }}/lib"
- name: Template ntfy config + compose
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  loop:
    - { src: server.yml.j2, dest: "{{ ntfy_root_dir }}/config/server.yml" }
    - { src: client.yml.j2, dest: "{{ ntfy_root_dir }}/config/client.yml" }
    - { src: docker-compose.yml.j2, dest: "{{ ntfy_root_dir }}/compose/docker-compose.yml" }
  notify: Restart ntfy
- name: Deploy ntfy
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ ntfy_root_dir }}/compose"
    project_name: "ntfy"
    state: present
    pull: missing
