- name: Check if helm is installed
  command: which helm
  changed_when: false
  failed_when: helm_installed.rc not in [0,1]
  register: helm_installed

- name: Add a bitnami repository
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Setup PV & PVC
  kubernetes.core.k8s:
    state: present
    template: "fast-storage.yaml.j2"

- name: Deploy 'postgresql' from bitnami
  kubernetes.core.helm:
    name: postgresql
    chart_ref: bitnami/postgresql
    release_namespace: homelab
    chart_version: 12.1.14
    values: "{{ lookup('template', 'postgresql_values.yaml.j2') | from_yaml }}"
