- name: "Download latest version of LazyGit"
  command: |
    curl -fsSL -o lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v0.44.1/lazygit_{{lazygit_version}}_Linux_x86_64.tar.gz"

- name: "Extract lazygit"
  command: |
    tar -xf lazygit.tar.gz lazygit

- name: "Install lazygit"
  become: true
  command: |
    sudo install lazygit /usr/local/bin
