- name: Make directory for copying files
  ansible.builtin.command: |
    mkdir -p {{ arr_base_dir }}/compose && \
    mkdir -p {{ arr_base_dir }}/service/gluetun && \
    mkdir -p {{ arr_base_dir }}/service/qbittorrent && \
    mkdir -p {{ arr_base_dir }}/data && \
    mkdir -p {{ arr_base_dir }}/config && \
    mkdir -p {{ arr_out_dir }}/data
  become: true

- name: Change owner of arr base dir
  ansible.builtin.command: |
    chown -R {{ ansible_user }}:{{ ansible_user }} {{ arr_base_dir }}
  become: true

- name: Change owner of arr storage dir
  ansible.builtin.command: |
    chown -R {{ ansible_user }}:{{ ansible_user }} {{ arr_out_dir }}
  become: true



- name: Copy docker compose template
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ arr_base_dir }}/compose/{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  loop:
    - src: docker-compose.yml.j2
      dest: "docker-compose.yml"
    - src: env.j2
      dest: ".env"
  notify: Restart arr


- name: Ensure arr-compose is running
  community.docker.docker_compose_v2:
    project_src: "{{ arr_base_dir }}/compose"
    build: never
  become: false