arr_base_dir: "/media"
arr_out_dir: "/storage"
arr_vpn_user: "some-user"
arr_vpn_password: "some-password"
arr_vpn_regions: "Netherlands"
arr_nzbget_ext_port: "6789"
arr_prowlarr_ext_port: "9696"
arr_qbittorrent_ext_port: "8080"
arr_sonarr_ext_port: "8989"
arr_radarr_ext_port: "7878"
arr_lidarr_ext_port: "8686"
arr_bazarr_ext_port: "6767"
arr_jellyseerr_ext_port: "5055"
