- name: Create required directory structure
  ansible.builtin.command: |
    mkdir -p {{ config_dir }}/immich && \
      mkdir -p {{ immich_storage_location }} && \
      mkdir -p {{ immich_db_data_location }}

- name: Copy docker compose template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ config_dir }}/immich/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Copy .env template
  ansible.builtin.template:
    src: env.j2
    dest: "{{ config_dir }}/immich/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"


- name: Deploy immich using docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/immich"
