- name: setup-repository-syncthing
  become: true
  block:
    - name: apt key
      get_url:
        url: "{{ syncthing_key_url }}"
        dest: "{{ syncthing_key_dest }}"
        mode: 0644
      # https://github.com/ansible/ansible/issues/65687
      when: not ansible_check_mode
      tags:
        - syncthing
        - apt
        - key

    - name: apt repository
      template:
        src: syncthing.list.j2
        dest: /etc/apt/sources.list.d/syncthing.list
        mode: 0644
      tags:
        - syncthing
        - apt
        - repository
  when:
    - syncthing_origin is defined
    - syncthing_origin == 'upstream'

- name: package
  become: true
  package:
    name: "{{ syncthing_packages }}"
    update_cache: true
  tags:
    - syncthing
    - package

- name: template
  become: true
  template:
    src: systemd.j2
    dest: /etc/systemd/system/syncthing@.service
    mode: 0644
  notify: restart
  tags:
    - syncthing
    - systemd

- name: stat
  stat:
    path: /etc/systemd/system/syncthing@.service
  register: systemd_unit
  tags:
    - syncthing
    - stat


- name: user
  become: true
  user:
    name: syncthing
    comment: Syncthing
    system: true
    createhome: true
  when: syncthing_user == 'syncthing'
  tags:
    - syncthing
    - user


- name: service
  become: true
  systemd:
    name: "{{ item }}@{{ syncthing_user }}.service"
    enabled: true
    state: started
    daemon_reload: true
  with_items: "{{ syncthing_packages }}"
  when:
    - systemd_unit.stat.isreg is defined
    - systemd_unit.stat.isreg
  tags:
    - syncthing
    - service

- name: sysctl
  become: true
  template:
    src: sysctl.conf.j2
    dest: "{{ syncthing_sysctl_file }}"
    mode: 0644
  when:
    - syncthing_max_user_watches is defined
  notify:
    - apply sysctl settings
  tags:
    - syncthing
    - sysctl