hound_port: 8301
hound_server_name: hound
hound_data_dir: /var/local/hound/data
hound_user: "{{ ansible_user }}"
hound_config:
  max-concurrent-indexers: 2
  dbpath: data
  repos:
    SomeGitRepo:
      url: https://www.github.com/uknth/homelab.git
    LocalFolder:
      url: file:///home/uknth/Workspace
