- name: setup tailscale network
  become: true
  ansible.builtin.import_role:
    name: artis3n.tailscale
  vars:
    tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
    tailscale_args: "--reset"
