- name: Setup certificate using 'certbot'
  become: true
  ansible.builtin.import_role:
    name: "system/network/certbot"
  vars:
    certbot_install_method: package
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services:
      - nginx
    certbot_auto_renew: true
    certbot_auto_renew_hour: "3"
    certbot_auto_renew_minute: "30"
    certbot_admin_email: uknth@outlook.com
    certbot_cloudflare_email: uknth@outlook.com
    certbot_cloudflare_api_key: "{{ cloudflare_api_key }}"
    certbot_certs:
      - domains:
          - "*.homelab.uknth.me"
          - "homelab.uknth.me"


- name: Setup nginx to run on host
  become: true
  ansible.builtin.import_role:
    name: geerlingguy.nginx
  vars:
    nginx_remove_default_vhost: true
    nginx_error_log: "/var/log/nginx/error.log warn"
    nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"
    nginx_client_max_body_size: "1024m"
    nginx_vhosts:
      - listen: "80 default_server"
        server_name: "_"
        extra_parameters: |
          return       301 https://$host$request_uri;

      - listen: "443 ssl http2"
        server_name: "homelab.uknth.me"
        extra_parameters: |
          location / {
            proxy_pass http://pie-2.homelab.uknth.me:8080/;
          }
          ssl_certificate     /etc/letsencrypt/live/homelab.uknth.me/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/homelab.uknth.me/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

      - listen: "443 ssl http2"
        server_name: "blocky.homelab.uknth.me"
        extra_parameters: |
          location / {
            proxy_pass http://pie-2.homelab.uknth.me:4000/;
          }
          ssl_certificate     /etc/letsencrypt/live/homelab.uknth.me/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/homelab.uknth.me/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

      - listen: "443 ssl http2"
        server_name: "nas.homelab.uknth.me"
        extra_parameters: |
          location / {
            proxy_pass http://nas-1.homelab.uknth.me:5000/;
          }
          ssl_certificate     /etc/letsencrypt/live/homelab.uknth.me/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/homelab.uknth.me/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

      - listen: "443 ssl http2"
        server_name: "{{ homelab_jellyfin_domain_name }}"
        extra_parameters: |
          location / {
            proxy_pass http://hero-1.hnet:80/;
            proxy_set_header Host $http_host;
          }
          ssl_certificate     /etc/letsencrypt/live/homelab.uknth.me/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/homelab.uknth.me/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

      - listen: "443 ssl http2"
        server_name: "videos.homelab.uknth.me"
        extra_parameters: |
          location / {
            proxy_pass http://hero-1.hnet:80/;
            proxy_set_header Host $http_host;
          }
          ssl_certificate     /etc/letsencrypt/live/homelab.uknth.me/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/homelab.uknth.me/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

      - listen: "443 ssl"
        server_name: "music.homelab.uknth.me"
        extra_parameters: |
          location / {
            proxy_pass http://hero-1.homelab.uknth.me:80/;
            proxy_set_header Host $http_host;
          }
          ssl_certificate     /etc/letsencrypt/live/homelab.uknth.me/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/homelab.uknth.me/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

      - listen: "443 ssl http2"
        server_name: "pi-hole.homelab.uknth.me"
        extra_parameters: |
          location / {
            proxy_pass http://pie-1.hnet:80/;
            proxy_set_header Host $http_host;
          }
          ssl_certificate     /etc/letsencrypt/live/homelab.uknth.me/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/homelab.uknth.me/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

      - listen: "443 ssl http2"
        server_name: "homeassistant.homelab.uknth.me"
        extra_parameters: |
          location / {
            proxy_pass http://pie-3.hnet:8123/;
            proxy_set_header Host $http_host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection “upgrade”;
          }
          ssl_certificate     /etc/letsencrypt/live/homelab.uknth.me/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/homelab.uknth.me/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

      - listen: "443 ssl http2"
        server_name: "vault.homelab.uknth.me"
        extra_parameters: |
          location / {
            proxy_pass http://pie-2.hnet:14001/;
            proxy_set_header Host $http_host;
            client_max_body_size 200M;
          }
          ssl_certificate     /etc/letsencrypt/live/homelab.uknth.me/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/homelab.uknth.me/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

      - listen: "443 ssl http2"
        server_name: "photos.homelab.uknth.me"
        extra_parameters: |
          location / {
            proxy_pass http://sidekick-1.hnet:2283/;
            proxy_set_header Host $http_host;
          }
          ssl_certificate     /etc/letsencrypt/live/homelab.uknth.me/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/homelab.uknth.me/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

      - listen: "443 ssl http2"
        server_name: "whoogle.homelab.uknth.me"
        extra_parameters: |
          location / {
            proxy_pass http://sidekick-1.hnet:5000/;
            proxy_set_header Host $http_host;
          }
          ssl_certificate     /etc/letsencrypt/live/homelab.uknth.me/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/homelab.uknth.me/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

      - listen: "443 ssl http2"
        server_name: "sourcebot.homelab.uknth.me"
        extra_parameters: |
          location / {
            proxy_pass http://sidekick-1.hnet:3000/;
            proxy_set_header Host $http_host;
          }
          ssl_certificate     /etc/letsencrypt/live/homelab.uknth.me/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/homelab.uknth.me/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;