- name: Synchronize internet-monitoring directory.
  ansible.posix.synchronize:
    src: files/internet-monitoring
    dest: "{{ config_dir }}/"
    delete: false
    recursive: true
    perms: false
  notify: Restart internet-monitoring
  become: false

- name: Copy templated internet-monitoring files into place.
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ config_dir }}/internet-monitoring/{{ item.dest }}"
    mode: 0644
  loop:
    - src: docker-compose.yml.j2
      dest: docker-compose.yml
    - src: grafana-config.monitoring.j2
      dest: grafana/config.monitoring
    - src: prometheus.yml.j2
      dest: prometheus/prometheus.yml
    - src: prometheus-pinghosts.yaml.j2
      dest: prometheus/pinghosts.yaml
  notify: Restart internet-monitoring
  become: false

- name: Ensure internet-monitoring environment is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/internet-monitoring/"
    build: false
  become: false
