---
# Variables applied to all hosts in the 'linux' group (Debian/Ubuntu)

ansible_python_interpreter: /usr/bin/python3

# APT
apt_upgrade: true
apt_autoremove: true
apt_cache_valid_time: 3600

# Docker
docker_users:
  - "{{ user }}"

# NTP — IST-friendly pool
ntp_servers:
  - pool 0.in.pool.ntp.org iburst
  - pool 1.in.pool.ntp.org iburst
  - pool 2.in.pool.ntp.org iburst
