blocky_ext_port: 14001
blocky_ui_ext_port: 14002
blocky_block_ads_list:
  - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  - http://sysctl.org/cameleon/hosts
  - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt

blocky_block_scams_list:
  - https://raw.githubusercontent.com/blocklistproject/Lists/refs/heads/master/scam.txt
  - https://raw.githubusercontent.com/blocklistproject/Lists/refs/heads/master/fraud.txt

blocky_block_malware_list:
  - https://raw.githubusercontent.com/blocklistproject/Lists/refs/heads/master/malware.txt

blocky_domain_mapping:
- {name: "dash.puhome.net", ip: "10.0.2.2"}
- {name: "puhome.net", ip: "10.0.2.2"}