vw_root_dir: "{{ config_dir }}/vaultwarden"
vw_data_dir: "{{ vw_root_dir }}/data"
vw_server_version: latest
vw_ext_port: 14001
vw_host: "vault.some-domain.com"
vw_admin_token: "some-random-token"
vw_smtp_host: "mail.smtp2go.com"
vw_smtp_port: 587
vw_smtp_security: "starttls"
vw_smtp_from: "smtp-from"
vw_smtp_user: "smtp-user"
vw_smtp_password: "smtp-password"
vw_signups_domains_whitelist: "some-domain.me,gmail.com,outlook.com"