vault_port: "9001"
vault_admin_token: "vault-admin-token"
vault_signup_domains_whitelist: "uknth.me,gmail.com,outlook.com"
vault_smtp_host: "smtp-mail.outlook.com"
vault_smtp_port: "587"
vault_smtp_security: "starttls"
vault_smtp_from: "mail@example.com"
vault_smtp_username: "mail@example.com"
vault_smtp_password: "some-smtp-password"
vault_smtp_auth_mechanism: "Login"
