---
# Domain names configuration (related services need to be enabled).
domain_name_enable: false
domain_name: "homelab.uknth.me"
domain_grafana: "grafana" # to access grafana via: http://grafana.homelab.uknth.me
domain_prometheus: "prometheus" # to access prometheus via: http://prometheus.homelab.uknth.me

# Internet monitoring configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "{{ vault_monitoring_grafana_admin_password }}"
monitoring_speedtest_interval: 60m
monitoring_ping_interval: 5s
monitoring_ping_hosts: # [URL];[HUMAN_READABLE_NAME]
  - http://www.google.com/;google.com
  - https://github.com/;github.com
  - https://www.apple.com/;apple.com

# Prometheus configuration.
prometheus_monitor_prometheus: false
prometheus_node_exporter_targets:
  - "sidekick-1.homelab.uknth.me:9100"
  - "hero-1.homelab.uknth.me:9100"
  - "workstation-1.homelab.uknth.me:9100"
prometheus_extra_scrape_configs: ""
prometheus_tsdb_retention_time: 30d

prometheus_dns_exporter_targets:
  - "sidekick-1.homelab.uknth.me:4000"
