- name: Make directory for copying files
  ansible.builtin.command: |
    mkdir -p {{ config_dir }}/portainer/data

- name: "Install portainer"
  ansible.builtin.import_role:
    name: ansible-portainer
  vars:
    persistent_data_path: "{{ config_dir }}/portainer/data:/data"
    auth_method: 1
    admin_user: "uknth"
    admin_password: "{{ portainer_admin_password }}"
