- name: setup ntp on hosts
  become: true
  ansible.builtin.import_role:
    name: geerlingguy.ntp
  vars:
    ntp_manage_config: true
    ntp_servers:
      - time1.google.com,
      - 0.in.pool.ntp.org,
      - 1.in.pool.ntp.org,
      - clock.fmt.he.net
