- name: Get user info for ansible_user
  ansible.builtin.user:
    name: "{{ ansible_user }}"
  register: user_info

- name: Make directory for copying files
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_info.uid }}"
    group: "{{ user_info.group }}"
  loop:
    - "{{ media_base_dir }}/config/gluetun"
    - "{{ media_base_dir }}/service/gluetun"
    - "{{ media_base_dir }}/config/qbittorrent"
    - "{{ media_base_dir }}/service/qbittorrent"
    - "{{ media_base_dir }}/config/qbittorrent-portfw"
    - "{{ media_base_dir }}/config/nzbget"
    - "{{ media_base_dir }}/service/nzbget"
    - "{{ media_base_dir }}/config/prowlarr"
    - "{{ media_base_dir }}/config/sonarr"
    - "{{ media_base_dir }}/config/radarr"
    - "{{ media_base_dir }}/config/lidarr"
    - "{{ media_base_dir }}/config/bazarr"
    - "{{ media_base_dir }}/config/ytdl-sub"
    - "{{ media_base_dir }}/config/jellyseerr"
    - "{{ media_base_dir }}/config/whisparr"
    - "{{ media_base_dir }}/config/unpackerr"
    - "{{ media_base_dir }}/logs/unpackerr"
    - "{{ media_out_dir }}/data/music"
    - "{{ media_out_dir }}/data/usenet"
    - "{{ media_out_dir }}/data/torrent"
    - "{{ media_out_dir }}/data/shows"
    - "{{ media_out_dir }}/data/movies"
    - "{{ media_out_dir }}/data/books"
    - "{{ media_out_dir }}/data/whisparr"
    - "{{ media_out_dir }}/data/yt"
    - "{{ media_base_dir }}/compose/arr"
  become: true

- name: Copy docker compose template
  ansible.builtin.template:
    src: "templates/{{ item.src }}"
    dest: "{{ media_base_dir }}/compose/arr/{{ item.dest }}"
    owner: "{{ user_info.uid }}"
    group: "{{ user_info.group }}"
    mode: "0644"
  loop:
    - src: docker-compose.yml.j2
      dest: "docker-compose.yml"
    - src: env.j2
      dest: ".env"
  vars:
    puid: "{{ user_info.uid }}"
    pgid: "{{ user_info.group }}"
  notify: Restart arr

- name: Ensure arr-compose is running
  community.docker.docker_compose_v2:
    project_src: "{{ media_base_dir }}/compose/arr"
    build: never
  become: false