---
certbot_create_command: "certbot certonly --noninteractive --dns-cloudflare --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }}"
certbot_keep_updated: yes
certbot_create_method: standalone
certbot_cloudflare_acme_server: "https://acme-v02.api.letsencrypt.org/directory"
